GET http://localhost:5001

###
GET http://localhost:5001/api/waitlist/count
###
POST http://localhost:5001/api/waitlist/register
Content-Type: application/json
{
  "email": "example@example.com",
  "name": "John Doe"
}