"""fixed notifications

Revision ID: 0e1fecc2f1ee
Revises: e6fc0758c2e0
Create Date: 2025-12-19 03:48:52.535365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1fecc2f1ee'
down_revision = 'e6fc0758c2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_friend_requests_sender_id'))
        batch_op.drop_index(batch_op.f('idx_friend_requests_status'))

    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_permissions_permission_id'))
        batch_op.drop_index(batch_op.f('idx_user_permissions_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_permissions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_permissions_permission_id'), ['permission_id'], unique=False)

    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_friend_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_friend_requests_sender_id'), ['sender_id'], unique=False)

    # ### end Alembic commands ###
