"""Add wallet models

Revision ID: 226ce42ea7a0
Revises: 6e01281eaa26
Create Date: 2026-02-18 00:30:07.091457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226ce42ea7a0'
down_revision = '6e01281eaa26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=50), nullable=False),
    sa.Column('to_currency', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('min_amount', sa.Integer(), nullable=True),
    sa.Column('max_amount', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sf_coins', sa.Integer(), nullable=True),
    sa.Column('premium_gems', sa.Integer(), nullable=True),
    sa.Column('event_tokens', sa.Integer(), nullable=True),
    sa.Column('total_coins_earned', sa.Integer(), nullable=True),
    sa.Column('total_coins_spent', sa.Integer(), nullable=True),
    sa.Column('daily_earning_limit', sa.Integer(), nullable=True),
    sa.Column('daily_coins_earned', sa.Integer(), nullable=True),
    sa.Column('last_earning_reset', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('currency_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['user_wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_transactions')
    op.drop_table('user_wallets')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
