"""adding more acheivements

Revision ID: 29710829c39a
Revises: d659945d25c6
Create Date: 2025-11-29 01:52:22.539951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29710829c39a'
down_revision = 'd659945d25c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'startups', ['startup_id'], ['id'])

    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key(None, 'chat_messages', ['reply_to_id'], ['id'])
        batch_op.create_foreign_key(None, 'chat_conversations', ['conversation_id'], ['id'])

    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'chat_conversations', ['conversation_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('conversation_user_reads', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'chat_conversations', ['conversation_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('goal_milestones', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'project_goals', ['goal_id'], ['id'])

    with op.batch_alter_table('growth_metrics', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'startups', ['startup_id'], ['id'])

    with op.batch_alter_table('idea_bookmarks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'ideas', ['idea_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('idea_comments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'ideas', ['idea_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])

    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'])

    with op.batch_alter_table('join_requests', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'startups', ['startup_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('knowledge', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])

    with op.batch_alter_table('knowledge_bookmarks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'knowledge', ['knowledge_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('knowledge_comments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'knowledge', ['resource_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])

    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post_media', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('project_goals', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'startups', ['startup_id'], ['id'])

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('resource_downloads', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'knowledge', ['resource_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('resource_likes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'knowledge', ['resource_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('resource_views', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'knowledge', ['resource_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('startup_bookmarks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'startups', ['startup_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('startup_documents', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'startups', ['startup_id'], ['id'])

    with op.batch_alter_table('startup_members', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'startups', ['startup_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'])

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('story_views', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'stories', ['story_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'ideas', ['idea_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['assigned_to'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'startups', ['startup_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'ideas', ['idea_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('team_performance', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'startups', ['startup_id'], ['id'])

    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'achievements', ['achievement_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=191),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=191),
               existing_nullable=False)

    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('team_performance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('story_views', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('startup_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('startup_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('startup_bookmarks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('resource_views', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('resource_likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('resource_downloads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('project_goals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('post_media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('knowledge_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('knowledge_bookmarks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('knowledge', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('join_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('idea_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('idea_bookmarks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('growth_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('goal_milestones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('conversation_user_reads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
