"""add storage_used_mb to users

Revision ID: 387cd3adcce8
Revises: 6b2712972bca
Create Date: 2026-02-28 22:08:24.936243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387cd3adcce8'
down_revision = '6b2712972bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=750), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=750), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_label', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('impact_score', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('startup_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('invited_user_id', sa.Integer(), nullable=False),
    sa.Column('invited_by_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'expired', name='invitationstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('startup_id', 'invited_user_id', name='unique_startup_invitation')
    )
    with op.batch_alter_table('startup_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size_mb', sa.Float(), nullable=True))
        batch_op.drop_column('file_size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startup_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.INTEGER(), nullable=True))
        batch_op.drop_column('file_size_mb')

    op.drop_table('startup_invitations')
    op.drop_table('ai_news_articles')
    # ### end Alembic commands ###
