"""Add image_url column to ideas table

Revision ID: 6adfcc475543
Revises: 45d7a5dc25db
Create Date: 2026-01-22 19:32:14.047487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6adfcc475543'
down_revision = '45d7a5dc25db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('project_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('team_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('members_involved', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('visible_by', sa.String(length=50), nullable=True))

    with op.batch_alter_table('startup_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_by', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startup_documents', schema=None) as batch_op:
        batch_op.drop_column('visible_by')

    with op.batch_alter_table('project_goals', schema=None) as batch_op:
        batch_op.drop_column('visible_by')
        batch_op.drop_column('members_involved')
        batch_op.drop_column('team_size')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('expiry', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###
