"""Add last_login_ip to user

Revision ID: 6e01281eaa26
Revises: 6adfcc475543
Create Date: 2026-01-26 22:51:02.592281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e01281eaa26'
down_revision = '6adfcc475543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_send_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('email_account_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach_email_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=False),
    sa.Column('smtp_password_encrypted', sa.Text(), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('hourly_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_email_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_email_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('outreach_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('max_emails', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_account_id'], ['outreach_email_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_campaigns_user_id'), ['user_id'], unique=False)

    op.create_table('outreach_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['outreach_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'email', name='uq_outreach_campaign_email')
    )
    with op.batch_alter_table('outreach_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_contacts_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('outreach_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['outreach_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=255), nullable=True))

    with op.batch_alter_table('join_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_links', sa.JSON(), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('entity_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('entity_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('push_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('push_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_notifications_actor_id_users', 'users', ['actor_id'], ['id'])


    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donation_message', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_ip', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_ip')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('donation_message')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('push_sent_at')
        batch_op.drop_column('push_sent')
        batch_op.drop_column('email_sent_at')
        batch_op.drop_column('email_sent')
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')
        batch_op.drop_column('priority')
        batch_op.drop_column('category')
        batch_op.drop_column('actor_id')

    with op.batch_alter_table('join_requests', schema=None) as batch_op:
        batch_op.drop_column('media_links')

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_column('link')

    op.drop_table('outreach_drafts')
    with op.batch_alter_table('outreach_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_contacts_campaign_id'))

    op.drop_table('outreach_contacts')
    with op.batch_alter_table('outreach_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_campaigns_user_id'))

    op.drop_table('outreach_campaigns')
    with op.batch_alter_table('outreach_email_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_email_accounts_user_id'))

    op.drop_table('outreach_email_accounts')
    op.drop_table('outreach_send_jobs')
    # ### end Alembic commands ###
