"""changing growth_metric relationship 4

Revision ID: b330d3d3c8f5
Revises: e4eef48b8146
Create Date: 2025-11-21 21:10:21.176723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b330d3d3c8f5'
down_revision = 'e4eef48b8146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startup_members', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('founder', 'contributor', 'investor', 'advisor', 'mentor', 'partner', 'admin', 'moderator', 'member', 'technical_lead', 'engineering_manager', 'backend_engineer', 'frontend_engineer', 'fullstack_engineer', 'mobile_engineer', 'software_architect', 'qa_engineer', 'test_automation_engineer', 'devops_engineer', 'cloud_engineer', 'sre', 'infrastructure_engineer', 'platform_engineer', 'cybersecurity_engineer', 'data_scientist', 'data_engineer', 'machine_learning_engineer', 'ai_engineer', 'mlops_engineer', 'data_analyst', 'ai_researcher', 'product_manager', 'product_owner', 'ux_designer', 'ui_designer', 'product_designer', 'ux_researcher', 'growth_engineer', 'growth_marketer', 'seo_specialist', 'content_strategist', name='userroles'),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('founder', 'contributor', 'investor', 'advisor', 'mentor', 'partner', 'admin', 'moderator', 'member', 'technical_lead', 'engineering_manager', 'backend_engineer', 'frontend_engineer', 'fullstack_engineer', 'mobile_engineer', 'software_architect', 'qa_engineer', 'test_automation_engineer', 'devops_engineer', 'cloud_engineer', 'sre', 'infrastructure_engineer', 'platform_engineer', 'cybersecurity_engineer', 'data_scientist', 'data_engineer', 'machine_learning_engineer', 'ai_engineer', 'mlops_engineer', 'data_analyst', 'ai_researcher', 'product_manager', 'product_owner', 'ux_designer', 'ui_designer', 'product_designer', 'ux_researcher', 'growth_engineer', 'growth_marketer', 'seo_specialist', 'content_strategist', name='userroles'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('founder', 'contributor', 'investor', 'advisor', 'mentor', 'partner', 'admin', 'moderator', 'member', 'technical_lead', 'engineering_manager', 'backend_engineer', 'frontend_engineer', 'fullstack_engineer', 'mobile_engineer', 'software_architect', 'qa_engineer', 'test_automation_engineer', 'devops_engineer', 'cloud_engineer', 'sre', 'infrastructure_engineer', 'platform_engineer', 'cybersecurity_engineer', 'data_scientist', 'data_engineer', 'machine_learning_engineer', 'ai_engineer', 'mlops_engineer', 'data_analyst', 'ai_researcher', 'product_manager', 'product_owner', 'ux_designer', 'ui_designer', 'product_designer', 'ux_researcher', 'growth_engineer', 'growth_marketer', 'seo_specialist', 'content_strategist', name='userroles'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('startup_members', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('founder', 'contributor', 'investor', 'advisor', 'mentor', 'partner', 'admin', 'moderator', 'member', 'technical_lead', 'engineering_manager', 'backend_engineer', 'frontend_engineer', 'fullstack_engineer', 'mobile_engineer', 'software_architect', 'qa_engineer', 'test_automation_engineer', 'devops_engineer', 'cloud_engineer', 'sre', 'infrastructure_engineer', 'platform_engineer', 'cybersecurity_engineer', 'data_scientist', 'data_engineer', 'machine_learning_engineer', 'ai_engineer', 'mlops_engineer', 'data_analyst', 'ai_researcher', 'product_manager', 'product_owner', 'ux_designer', 'ui_designer', 'product_designer', 'ux_researcher', 'growth_engineer', 'growth_marketer', 'seo_specialist', 'content_strategist', name='userroles'),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
