"""changing startup attributes

Revision ID: c6f1e395ba79
Revises: b4371cf362a5
Create Date: 2025-11-25 20:28:31.123248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f1e395ba79'
down_revision = 'b4371cf362a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tech_stack', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.drop_column('tech_stack')

    # ### end Alembic commands ###
