"""changing startup attributes

Revision ID: d31214d34cf7
Revises: 1d7710d8ac6f
Create Date: 2025-11-25 03:24:14.974103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31214d34cf7'
down_revision = '1d7710d8ac6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('startup_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revenue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('funding_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('funding_round', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('burn_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('runway_months', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valuation', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('financial_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('logo_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('banner_path', sa.String(length=500), nullable=True))
        batch_op.drop_column('banner_data')
        batch_op.drop_column('logo_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_data', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('banner_data', sa.BLOB(), nullable=True))
        batch_op.drop_column('banner_path')
        batch_op.drop_column('logo_path')
        batch_op.drop_column('financial_notes')
        batch_op.drop_column('valuation')
        batch_op.drop_column('runway_months')
        batch_op.drop_column('burn_rate')
        batch_op.drop_column('funding_round')
        batch_op.drop_column('funding_amount')
        batch_op.drop_column('revenue')

    op.drop_table('startup_documents')
    # ### end Alembic commands ###
