"""changing startup attributes 2

Revision ID: d659945d25c6
Revises: c6f1e395ba79
Create Date: 2025-11-25 21:20:07.976794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd659945d25c6'
down_revision = 'c6f1e395ba79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startup_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('banner_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.drop_column('banner_url')
        batch_op.drop_column('logo_url')

    with op.batch_alter_table('startup_documents', schema=None) as batch_op:
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
