"""Added credits to UserWallet

Revision ID: dae228d06db0
Revises: 226ce42ea7a0
Create Date: 2026-02-20 15:58:19.759168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae228d06db0'
down_revision = '226ce42ea7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('exchange_rates')
    # with op.batch_alter_table('startup_members', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user_wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('daily_earnings', sa.Integer(), nullable=True))
        batch_op.drop_column('daily_coins_earned')

    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('xp_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))
        batch_op.alter_column('transaction_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('currency_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('reference_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_wallet_tx_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_wallet_tx_user_id', type_='foreignkey')
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('reference_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('currency_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('transaction_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('xp_amount')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user_wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_coins_earned', sa.INTEGER(), nullable=True))
        batch_op.drop_column('daily_earnings')
        batch_op.drop_column('credits')

    with op.batch_alter_table('startup_members', schema=None) as batch_op:
        batch_op.drop_column('admin')

    op.create_table('exchange_rates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('from_currency', sa.VARCHAR(length=50), nullable=False),
    sa.Column('to_currency', sa.VARCHAR(length=50), nullable=False),
    sa.Column('rate', sa.FLOAT(), nullable=False),
    sa.Column('min_amount', sa.INTEGER(), nullable=True),
    sa.Column('max_amount', sa.INTEGER(), nullable=True),
    sa.Column('valid_from', sa.DATETIME(), nullable=True),
    sa.Column('valid_to', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
