"""changing growth_metric relationship 3

Revision ID: e4eef48b8146
Revises: 
Create Date: 2025-11-21 00:40:52.201601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4eef48b8146'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growth_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('metric_type', sa.Enum('user_growth', 'revenue', 'market_share', 'overall'), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('growth_percentage', sa.Float(), nullable=True),
    sa.Column('user_growth_percentage', sa.Float(), nullable=True),
    sa.Column('revenue_amount', sa.Float(), nullable=True),
    sa.Column('market_share_percentage', sa.Float(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('growth_metrics')
    # ### end Alembic commands ###
