"""Add foreign key constraint 5

Revision ID: e6fc0758c2e0
Revises: 55cb5f25f54c
Create Date: 2025-12-16 11:02:16.085718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6fc0758c2e0'
down_revision = '55cb5f25f54c'
branch_labels = None
depends_on = None


def upgrade():
    

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.alter_column('granted_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        
        batch_op.create_index(batch_op.f('ix_user_permissions_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_user_permissions_granted_by'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['granted_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_permissions_granted_by'), 'users', ['granted_by'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_user_permissions_user_id'))
        batch_op.create_index(batch_op.f('idx_user_permissions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_permissions_expires'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_permissions_active'), ['user_id', 'permission_id', 'expires_at'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('granted_by',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_key'))
        batch_op.drop_index(batch_op.f('ix_permissions_category'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_friend_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_friend_requests_sender_id'), ['sender_id'], unique=False)

    # ### end Alembic commands ###
